parameters:
    database_host: mdc-dbs-mysql.mysql.database.azure.com
    database_port: 3306
    database_name: mdc_produccion
    database_user: dc9cw2m5x7479e@mdc-dbs-mysql
    database_password: 2u33e4t3$4.
    mailer_transport: smtp
    mailer_host: smtp.1and1.com
    mailer_user: noreply@medeconsult.com
    mailer_password: Medeconsult1.
    mailer_port: 587
    secret: 74b4ba9789a27630d011ab641d17f04be362ee22
    paypal.express_checkout.username: sdk-three_api1.sdk.com
    paypal.express_checkout.password: QFZCWN5HZM8VBG7Q
    paypal.express_checkout.signature: A-IzJhZZjhg29XQ2qnhapuwxIDzyAZQ92FRP5dqBzVesOkzbdUONzmOU
